import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../components/Navbar";
import { Landing } from "../components/Landing";
import { Projects } from "../components/Projects";
import { Technologies } from "../components/Technologies";
import { Footer } from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/a-logo.png" />
      </Head>
      <div className="bg-mygreen-light">
        <Navbar />
        <Landing />
      </div>
      <Projects />
      <Technologies />
      <Footer />
    </div>
  );
};

export default Home;
